<?php

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *  
 * Triangle
 * Tn = n(n + 1) / 2
 * 1, 3, 6, 10, 15, ...
 * Pentagonal
 * Pn = n(3n−1)/2
 * 1, 5, 12, 22, 35, ...
 * Hexagonal
 * Hn = n(2n−1)
 * 1, 6, 15, 28, 45, ...
 *  
 * It can be verified that T285 = P165 = H143 = 40755.
 * Find the next triangle number that is also pentagonal and hexagonal .
 *  
 * Answer: 1533776805
 */

function isPentagonal($n)
{
    // Compute the pentagonal formula for n.
    $p = (sqrt(24 * $n + 1) + 1) / 6;
    return $p == (int) $p;
}

function isHexagonal($n)
{
    // Compute the hexagonal formula for n.
    $h = (sqrt(8 * $n + 1) + 1) / 4;
    return $h == (int) $h;
}

// test runner
$n = 286; // Starting from 286, because need to find the next number after 40755. 40755 is the 285th triangle number.

while (true) {

    $t = $n * ($n + 1) / 2; // Compute the triangle number for n.

    if (isPentagonal($t) && isHexagonal($t)) {
        echo $t;
        break;
    }

    $n++;
}

echo "\n";
